- name: Get join command
  changed_when: false
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
