- name: Cleanup SSH localhost
  gather_facts: true
  hosts: localhost
  roles:
    - ssh

- name: Insert SSH Pubkey
  gather_facts: true
  become: true
  hosts: all
  roles:
    - remote_ssh

- name: Prerequisite Kubernetes Task
  gather_facts: true
  become: true
  hosts: all
  roles:
    - prerequisite

- name: Setup Master
  gather_facts: true
  become: true
  hosts: plane
  roles:
    - k8s-master

- name: Get Cluster Information
  gather_facts: true
  become: true
  hosts: plane
  roles:
    - cluster-information


- name: Join Cluster Worker
  gather_facts: true
  become: true
  hosts: worker
  roles:
    - join-cluster
